vim.g.mapleader = " "
O = vim.o
O.clipboard = 'unnamedplus'
O.expandtab = true
O.ignorecase = true
O.number = false
O.relativenumber = false
O.shiftwidth = 2
O.smartcase = true
O.tabstop = 2
O.termguicolors = true
O.undofile = true
O.updatetime = 0
