vim.g.mapleader = ' '
-- this said vim.o should be avoided and I should use vim.opt?? https://www.youtube.com/watch?v=Cp0iap9u29c
O = vim.opt
-- O.textwidth = 120
O.clipboard = 'unnamedplus'
O.expandtab = true
O.ignorecase = true
O.number = true
O.relativenumber = true
O.shiftwidth = 2
O.smartcase = true
O.tabstop = 2
O.termguicolors = true
O.undofile = true
-- O.updatetime = 0
O.hlsearch = false
